# Generated by Django 5.2.17 on 2026-09-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionlisting',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('adopted', 'Adopted'), ('withdrawn', 'Withdrawn'), ('draft', 'Draft')], default='available', max_length=20),
        ),
    ]
