# Generated by Django 5.2.17 on 2026-10-05 07:48

import django.db.models.deletion
from django.db import migrations, models


def backfill_kinds(apps, schema_editor):
    """AD22 · rows that predate `kind`: every all-skipped ladder is a placement."""
    from listings.kinds import backfill_inquiry_kinds
    backfill_inquiry_kinds(apps.get_model("listings", "AdoptionInquiry"),
                           apps.get_model("listings", "AdoptionStage"))


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_anonymized_at'),
        ('listings', '0006_listing_status_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptioninquiry',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adoptioninquiry',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('not_a_fit', 'Not A Fit'), ('requirements_not_met', 'Requirements Not Met'), ('no_response', 'No Response'), ('other', 'Other'), ('another_adopter_chosen', 'Another Adopter Chosen'), ('adopter_withdrew', 'Adopter Withdrew'), ('listing_withdrawn', 'Listing Withdrawn'), ('placement_declined', 'Placement Declined'), ('placement_cancelled', 'Placement Cancelled'), ('placement_expired', 'Placement Expired')], max_length=30),
        ),
        migrations.AddField(
            model_name='adoptioninquiry',
            name='ended_by_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='adoptioninquiry',
            name='kind',
            field=models.CharField(choices=[('inquiry', 'Inquiry'), ('placement', 'Placement')], default='inquiry', max_length=20),
        ),
        migrations.AddField(
            model_name='adoptioninquiry',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_kinds, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='adoptioninquiry',
            constraint=models.UniqueConstraint(condition=models.Q(('reserved_at__isnull', False), ('status', 'active')), fields=('listing',), name='uq_adoption_inquiry_one_reserved'),
        ),
    ]
