# Generated by Django 5.2.17 on 2026-09-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagip', '0006_strayreport_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportoffer',
            name='contact_share_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportoffer',
            name='contact_share_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rescuecase',
            name='contact_share_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rescuecase',
            name='contact_share_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strayreport',
            name='contact_share_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='strayreport',
            name='contact_share_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
