# Generated by Django 5.2.17 on 2026-09-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagip', '0007_contact_share_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='strayreport',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
