# Generated by Django 5.2.17 on 2026-10-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagip', '0008_strayreport_hidden_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='strayreport',
            name='alert_held',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
