# Generated by Django 5.2.17 on 2026-09-23 11:51

from django.db import migrations, models


def backfill_location(apps, schema_editor):
    Shift = apps.get_model("volunteer", "VolunteerShift")
    Address = apps.get_model("accounts", "Address")
    for shift in Shift.objects.filter(city=""):
        addr = (Address.objects.filter(account_id=shift.shelter_account_id, is_primary=True).first()
                or Address.objects.filter(account_id=shift.shelter_account_id).first())
        if addr is None:
            continue
        shift.address_line1, shift.barangay = addr.line1 or "", addr.barangay or ""
        shift.city, shift.province = addr.city or "", addr.province or ""
        shift.save(update_fields=["address_line1", "barangay", "city", "province"])


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_volunteersignup_idx_volunteer_signup_listing'),
        ('accounts', '0009_account_anonymized_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteershift',
            name='address_line1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='volunteershift',
            name='barangay',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='volunteershift',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='volunteershift',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='volunteershift',
            name='meeting_point',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='volunteershift',
            name='province',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='volunteershift',
            name='title',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.RunPython(backfill_location, migrations.RunPython.noop),
    ]
