# Generated by Django 5.2.17 on 2026-09-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_anonymized_at'),
        ('listings', '0005_listing_preference'),
        ('volunteer', '0003_shift_details'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='volunteersignup',
            name='idx_volunteer_signup_pair',
        ),
        migrations.AddConstraint(
            model_name='volunteersignup',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['cancelled', 'declined']), _negated=True), fields=('shift', 'volunteer_account'), name='volunteer_signup_live_pair'),
        ),
    ]
