# Generated by Django 5.2.17 on 2026-09-23 16:22

from django.db import migrations, models


def backfill_cancelled_by(apps, schema_editor):
    """P4 · every existing cancelled signup predates the `cancelled_by` column, so infer it
    from the shift it belongs to: a `closed` shift means the shelter's cascade cancelled it
    (ShelterShiftCancelView), anything else means the volunteer cancelled it themselves
    (SignupCancelView) — the only two paths that produced a cancelled row before this column
    existed."""
    Signup = apps.get_model("volunteer", "VolunteerSignup")
    Signup.objects.filter(status="cancelled", shift__status="closed").update(
        cancelled_by="shelter")
    Signup.objects.filter(status="cancelled").exclude(shift__status="closed").update(
        cancelled_by="volunteer")


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_live_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteersignup',
            name='attendance_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteersignup',
            name='cancelled_by',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='volunteershift',
            name='type',
            field=models.CharField(choices=[('walking', 'Dog walking'), ('feeding', 'Feeding'), ('visitor', 'Visitor'), ('event', 'Event'), ('facility', 'Facility care'), ('transport', 'Transport')], default='walking', max_length=12),
        ),
        migrations.RunPython(backfill_cancelled_by, migrations.RunPython.noop),
    ]
