# Generated by Django 5.2.17 on 2026-09-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0003_alter_moderationflag_reviewed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationflag',
            name='target_type',
            field=models.CharField(choices=[('account', 'Account'), ('listing', 'Listing'), ('report', 'Report'), ('qr', 'Qr'), ('message', 'Message'), ('story', 'Story'), ('shift', 'Shift')], max_length=10),
        ),
    ]
